print("---------------------------------")
print("|\t\tEscape sequences\t\t|")
print("---------------------------------")
print("|\\a\t\t|\t\tBell(alert)\t\t|")
print("---------------------------------")
print("|\\b\t\t|\t\tBackspace\t\t|")
print("---------------------------------")
print("|\\n\t\t|\t\tNew line\t\t|")
print("---------------------------------")
print("|\\\ \t|\t\tBackslash \\ \t|")
print("---------------------------------")
print("|\\\"\t\t|Double quotation mark \"|")
print("---------------------------------")
print("|\\\'\t\t|  One quotation mark \' |")
print("---------------------------------")